version: "3"
services:

  apm-server:
    container_name: apm-server-container
    image: store/elastic/apm-server:6.7.2
    user: root
    ports:
      - "7200:7200"
    depends_on: ["elasticsearch", "kibana"]
    volumes:
      - ./apm-conf/apm-server.yml:/usr/share/apm-server/apm-server.yml
    command: /usr/share/apm-server/apm-server -e -c /usr/share/apm-server/apm-server.yml -E apm-server.host=apm-server:7200 --strict.perms=false
    networks: 
      - lab-network
  
  django-agent-elk:
    container_name: django-agent-elk-container
    image: lyonn/django-agent-elk:demo
    ports:
      - "8000:8000"
    depends_on: ["apm-server"]
    environment:
      - ELASTIC_APM_SERVER_URL: http://apm-server:7200
      - ELASTIC_APM_SERVER_PORT: 7200
    volumes:
      #The commented sections below enables Metricbeat to monitor the Docker host rather than the Metricbeat container. These are used by the system module.
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      #Allows us to report on docker from the hosts information.
      - /var/run/docker.sock:/var/run/docker.sock
      #We mount the host filesystem so we can report on disk usage with the system module.
      - /:/hostfs:ro
    networks:
      - lab-network
      

  elasticsearch:
    container_name: elasticsearch-container
    image: docker.io/elasticsearch:6.7.2
    environment:
            discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
    networks:
      - lab-network

  kibana:
    container_name: kibana-container
    hostname: kibana
    image: docker.io/kibana:6.7.2
    #volumes:
    #  - ./kibana.yml:/usr/share/kibana/kibana.yml
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports: ['5601:5601']
    depends_on: ["elasticsearch"]
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/"]
      retries: 6
    networks:
      - lab-network
          
volumes:
  esdata:
    driver: local

networks: 
  lab-network:

